/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.CaixaModel;
import Model.DAO.CaixaDAO;
import Model.DAO.FuncionarioDAO;
import Model.DAO.LoginDAO;
import Model.FuncionarioModel;
import Model.LoginModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pedro
 */
public class CaixaView extends javax.swing.JFrame {
    
   private List <LoginModel> listaLogin;
   private List<FuncionarioModel> listaFuncionario;
    /**
     * Creates new form CaixaView
     */
    public CaixaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldValorInicialCaixa = new javax.swing.JTextField();
        jButtonAbrirCaixa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTabelaCaixa = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldValorTotal = new javax.swing.JTextField();
        jButtonFecharCaixa = new javax.swing.JButton();
        jTextFieldDataFechamento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel4.setText("jLabel4");

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de caixa");

        jLabel3.setText("Valor Inicial");

        jButtonAbrirCaixa.setText("Abrir Caixa");
        jButtonAbrirCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirCaixaActionPerformed(evt);
            }
        });

        jTableTabelaCaixa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Responsável", "Data Abertura", "Data fechamento", "Valor Inicial", "Valor Total", "Estado Caixa"
            }
        ));
        jScrollPane1.setViewportView(jTableTabelaCaixa);

        jLabel5.setText("Valor Total");

        jTextFieldValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorTotalActionPerformed(evt);
            }
        });

        jButtonFecharCaixa.setText("Fechar Caixa");
        jButtonFecharCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharCaixaActionPerformed(evt);
            }
        });

        jTextFieldDataFechamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataFechamentoActionPerformed(evt);
            }
        });

        jLabel6.setText("Data Fechamento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFecharCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldDataFechamento, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 173, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldValorInicialCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAbrirCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldValorInicialCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAbrirCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDataFechamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFecharCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAbrirCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirCaixaActionPerformed
        // pega a data
        String dataA, dataF, valorI, valorT, estado;
        int tamanho, tamanhoFuncionario;
        FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
        FuncionarioModel funcionarioModel = new FuncionarioModel();
        CaixaModel caixaModel = new CaixaModel();
        CaixaDAO caixaDAO = new CaixaDAO();
        LoginModel loginModel = new LoginModel();
        LoginDAO loginDAO = new LoginDAO();
        
        // Atribui valores ao CaixaMODEL - DATA, VALOR, ESTADO, RESPOSAVEL!
        
        Date data = new Date(System.currentTimeMillis());
        SimpleDateFormat formatarDate = new SimpleDateFormat("dd/MM/yyyy");
        String date = formatarDate.format(data);
        System.out.println("DATA:" + date);
        
        caixaModel.setDataAbertura(data);
        caixaModel.setDataFechamento(data); /// Mesma data 
        
        int valorInicial = Integer.parseInt(jTextFieldValorInicialCaixa.getText());
        
        caixaModel.setValorInicial(valorInicial);
        
        caixaModel.setValorTotal(0);
        
        caixaModel.setEstado("Aberto");
        System.out.println("CAIXA MODEL" + caixaModel);
        
         listaLogin = loginDAO.findAll();
         System.out.println("CAIXA MOssssassasaDEL" + listaLogin);
        
//recebe a ultima posição da lista de login

        
        tamanho = listaLogin.size();    
        loginModel = listaLogin.get(tamanho-1);
        System.out.println("a vale" + loginModel);
        
       
        
        //recebe nome que esta no model
        System.out.println("TESTE");
        System.out.println("LOGIN MODELaaaaaaaaaaaa" + loginModel);
        System.out.println("TESTE2");
        
        String nome = loginModel.getNomeLogin();
        int indice = loginModel.getIdLogin();
        funcionarioModel = loginModel.getFuncionario();
        System.out.println("indice"+indice + "Funcionario"+ funcionarioModel);
        //listaFuncionario = funcionarioDAO.findAll();
        //tamanhoFuncionario = listaFuncionario.size();
        
        int cod = funcionarioModel.getCodFuncionario();
        
        System.out.println("COOOOOOD"+ cod);
        
        funcionarioModel = funcionarioDAO.buscarFuncionario(cod);
        
        System.out.println("AMENO aAAAAAAA "+ funcionarioModel);
        
        // funcionario = funcionarioModel.getCodFuncionario();
      
        
     //   funcionarioModel = funcionario;
        
        
      //  int cod = funcionarioModel.getCodFuncionario();
        String codFuncionario = Integer.toString(funcionarioModel.getCodFuncionario());
        
            
        System.out.println("codFuncionariocccccccccc" + codFuncionario);
        //String a = loginDAO.buscarLogin();
        //SALVA CAIXA NO BANCO
     //   caixaModel.setFuncionario(funcionario.getCodFuncionario());
        caixaDAO.SalvarCaixa(caixaModel);
        
        //LIMPA O VALOR INICIAL
        jTextFieldValorInicialCaixa.setText("");
        
        //ATRIBUI VALORES (OBJETO) NA TABELA
        DefaultTableModel val = (DefaultTableModel) jTableTabelaCaixa.getModel();
       
        //Responsavel = "Funcionario"; // valor temporario
        dataA = Double.toString(caixaModel.getValorInicial());
        dataF = Double.toString(caixaModel.getValorTotal());
        valorI = date;
        valorT = date;
        estado = "Aberto";
        val.addRow(new String[]{codFuncionario, dataA, dataF, valorI, valorT, estado});
      
    }//GEN-LAST:event_jButtonAbrirCaixaActionPerformed

    private void jButtonFecharCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharCaixaActionPerformed
        int valorInicial, valorTotal;
        CaixaDAO caixaDAO = new CaixaDAO();
        CaixaModel caixaModel = new CaixaModel();
        
        // PEGA A DATA PARA FAZER O FECHAMENTO
        
        Date data = new Date(System.currentTimeMillis());
        SimpleDateFormat formatarDate = new SimpleDateFormat("dd/MM/yyyy");
        String date = formatarDate.format(data);
        
        // System.out.print(formatarDate.format(data));
        caixaModel.setDataAbertura(data);
        caixaModel.setDataFechamento(data); /// Mesma data 
        
        valorInicial = Integer.parseInt(jTextFieldValorInicialCaixa.getText());
        caixaModel.setValorInicial(valorInicial);
        
        valorTotal = Integer.parseInt(jTextFieldValorInicialCaixa.getText());
        caixaModel.setValorTotal(valorTotal);

        valorTotal = valorTotal + valorInicial;

        caixaModel.setValorTotal(valorTotal);

        jTextFieldDataFechamento.setText("");
        //    jTextFieldResponsavelCaixa.setText("");
        jTextFieldValorInicialCaixa.setText("");
        jTextFieldValorTotal.setText("");
        
        caixaDAO.atualizar(caixaModel);
        
        
        
        System.out.println(caixaModel);
       

    }//GEN-LAST:event_jButtonFecharCaixaActionPerformed
    
     private void UltimoLogin(List<LoginModel> logins) {
      
        listaLogin = logins;
        
        
        
            
    }
    
    
    private void jTextFieldValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorTotalActionPerformed

    private void jTextFieldDataFechamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataFechamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataFechamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaixaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaixaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaixaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaixaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaixaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrirCaixa;
    private javax.swing.JButton jButtonFecharCaixa;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTabelaCaixa;
    private javax.swing.JTextField jTextFieldDataFechamento;
    private javax.swing.JTextField jTextFieldValorInicialCaixa;
    private javax.swing.JTextField jTextFieldValorTotal;
    // End of variables declaration//GEN-END:variables
}
